---
- name: Global aliases
  ansible.builtin.copy:
    dest: /etc/profile.d/10-aliases.sh
    content: |
      {{ aliases }}
    owner: root
    group: root
    mode: 0644

- name: Default gitconfig
  ansible.builtin.copy:
    dest: /root/.gitconfig
    content: |
      {{ git_config }}
    owner: root
    group: root
    mode: 0644

- name: Download direct from URLs (limited exceptions)
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.file }}"
    mode: 0644
  loop: "{{ url_downloads }}"

- name: Add shell-integration commands
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "{{ item }}"
  loop: "{{ shell_integrations }}"

- name: Create "atuin" app sub-directories
  ansible.builtin.file:
    path: "/root/{{ item }}"
    state: directory
    mode: 0700
    owner: root
    group: root
  loop:
    - .config
    - .config/atuin

- name: Copy "atuin" config file
  ansible.builtin.template:
    src: config.toml.j2
    dest: /root/.config/atuin/config.toml
    owner: root
    group: root
    mode: 0600

- name: List of starship theme files          # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: ls -1 starship*.toml
    executable: /bin/bash
    chdir: "{{ role_path }}/files/"
  changed_when: false
  register: starship_files

- name: Copy starship theme files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ starship_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ starship_files.stdout_lines }}"

- name: Link main starship theme
  ansible.builtin.file:
    src: "{{ starship_path }}/starship.pastel-powerline.toml"
    dest: "{{ starship_path }}/starship.toml"
    state: link
    force: true
