[tools]
# Ansible
python = { version = "3.12", postinstall = "/root/.local/share/mise/installs/python/3.12/bin/python3.12 -m pip install --upgrade requests" }
pipx = "1.11"
"pipx:ansible-core" = { version = "2.18.6", depends = ["python", "pipx"], postinstall = "ansible-galaxy collection install -r ansible/requirements.yml" }
"pipx:ansible-lint" = "latest"
"pipx:yamllint" = "latest"

# Terraform
terraform = "1.2.9"
tflint = "latest"

# Security
checkov = "latest"
trufflehog = "latest"

# Miscellaneous
circleci = "latest"
editorconfig-checker = "latest"
jq = "latest"
task = "3.49"
packer = "1.11.2"
