---
# - Docs: https://taskfile.dev/
# - Examples: https://dev.to/stack-labs/introduction-to-taskfile-a-makefile-alternative-h92
version: '3'

dotenv: ['.env']

includes:
  apps: ./tasks/apps.yml
  debug: ./tasks/debug.yml
  devbox: ./tasks/devbox.yml
  grafix: ./tasks/grafix.yml
  net: ./tasks/net.yml
  proxmox: ./tasks/proxmox.yml
  rpi: ./tasks/rpi.yml
  tools: ./tasks/tools.yml

vars:
  ANSIBLE_DIR: ./ansible
  ANSIBLE_INVENTORY_PROXMOX: inventories/proxmox
  GLOBAL_DOMAIN: $MY_GLOBAL_DOMAIN
  PACKER_DIR: ./packer
  TERRAFORM_DIR: ./terraform
  WAIT_SECS_LONG: 120
  WAIT_SECS_MEDIUM: 30
  WAIT_SECS_SHORT: 5
