---
# Usage:
# - Include this template in Taskfile
# - Define SERVICE_VAR in Taskfile
version: '3'

vars:
  SERVICE_TF_DIR: '{{.TERRAFORM_DIR}}/{{.SERVICE_VAR}}'
  SERVICE_TF_STATE: '{{.TERRAFORM_STATE}}/{{.SERVICE_VAR}}.tfstate'
  SERVICE_ANSIBLE_PLAYBOOK: 'lxc-{{.SERVICE_VAR}}-provision.yml'

tasks:
  check-lxc-vars:
    internal: true
    cmds:
      - 'echo HOST={{.SERVICE_VAR}}.{{.GLOBAL_DOMAIN}}'
      - 'echo TF_DIR={{.SERVICE_TF_DIR}}'
      - 'echo TF_STATE={{.SERVICE_TF_STATE}}'
      - 'echo ANSIBLE_PLAYBOOK={{.SERVICE_ANSIBLE_PLAYBOOK}}'

  # Terraform operations
  create-lxc:
    internal: true
    dir: '{{.SERVICE_TF_DIR}}'
    preconditions:
      - sh: test -f {{.SERVICE_TF_STATE}}
        msg: "{{.SERVICE_TF_STATE}} not found"
    cmds:
      - terraform init -backend-config="path={{.SERVICE_TF_STATE}}"
      - terraform fmt && terraform validate
      - terraform apply -lock=false
      - terraform output

  destroy-lxc:
    internal: true
    dir: '{{.SERVICE_TF_DIR}}'
    preconditions:
      - sh: test -f {{.SERVICE_TF_STATE}}
        msg: "{{.SERVICE_TF_STATE}} not found"
    cmds:
      - terraform destroy -lock=false -compact-warnings

  update-dns:
    internal: true
    dir: '{{.SERVICE_TF_DIR}}'
    preconditions:
      - sh: test -f {{.SERVICE_TF_STATE}}
        msg: "{{.SERVICE_TF_STATE}} not found"
    cmds:
      - terraform init -backend-config="path={{.SERVICE_TF_STATE}}"
      - terraform fmt && terraform validate
      - |
        terraform apply     \
          -lock=false       \
          -compact-warnings \
          -parallelism=1    \
          -target=module.my_lxc.cloudflare_record.cname_records

  # Ansible operations
  patch-lxc:
    internal: true
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - |
        ansible-playbook \
          -i {{.ANSIBLE_INVENTORY_PROXMOX}} \
          proxmox-lxc-patch.yml \
          --extra-vars 'lxc_hostname={{.LXC_HOSTNAME}} lxc_id={{.LXC_ID}} lxc_proxmox_node={{.LXC_PROXMOX_NODE}} lxc_patch={{.PATCH_NAME}}'
    vars:
      LXC_HOSTNAME:
        sh: terraform -chdir={{.SERVICE_TF_DIR}} output -json my_lxc | jq -r '.lxc_hostname'
      LXC_ID:
        sh: terraform -chdir={{.SERVICE_TF_DIR}} output -json my_lxc | jq -r '.lxc_vmid'
      LXC_PROXMOX_NODE:
        sh: terraform -chdir={{.SERVICE_TF_DIR}} output -json my_lxc | jq -r '.lxc_proxmox_node'

  provision:
    internal: true
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - "ansible-playbook -i {{.ANSIBLE_INVENTORY_PROXMOX}} {{.SERVICE_ANSIBLE_PLAYBOOK}}"

  provision-app:
    internal: true
    dir: '{{.ANSIBLE_DIR}}'
    cmds:
      - 'ansible-playbook -i {{.ANSIBLE_INVENTORY_PROXMOX}} {{.SERVICE_ANSIBLE_PLAYBOOK}} --tag {{.APP_NAME | default ""}}'
