---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  APPS_HOST: "apps"
  SERVICE_VAR: "{{.APPS_HOST}}"

tasks:
  check:
    desc: 'Check "{{.APPS_HOST}}" host vars'
    cmds:
      - task: shared:check-lxc-vars

  # ? Terraform
  create-lxc:
    desc: 'Create "{{.APPS_HOST}}" host'
    cmds:
      - task: shared:create-lxc

  destroy-lxc:
    desc: 'Destroy "{{.APPS_HOST}}" host'
    cmds:
      - task: shared:destroy-lxc

  update-dns:
    desc: 'Update DNS records for "{{.APPS_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.APPS_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-traefik:
    desc: 'Provision "Traefik" on "{{.APPS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'traefik'}

  provision-booklore:
    desc: 'Provision "Booklore" on "{{.APPS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'booklore'}

  provision-glance:
    desc: 'Provision "Glance" on "{{.APPS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'glance'}

  provision-homepage:
    desc: 'Provision "Homepage" on "{{.APPS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'homepage'}

  provision-jotty:
    desc: 'Provision "Jotty" on "{{.APPS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'jotty'}

  provision-mealie:
    desc: 'Provision "Mealie" on "{{.APPS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'mealie'}
