---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  DEBUG_HOST: "debug"
  SERVICE_VAR: "{{.DEBUG_HOST}}"

tasks:
  check:
    desc: 'Check "{{.DEBUG_HOST}}" host vars'
    cmds:
      - task: shared:check-lxc-vars

  # ? Terraform
  create-lxc:
    desc: 'Create "{{.DEBUG_HOST}}" host'
    cmds:
      - task: shared:create-lxc

  destroy-lxc:
    desc: 'Destroy "{{.DEBUG_HOST}}" host'
    cmds:
      - task: shared:destroy-lxc

  update-dns:
    desc: 'Update DNS records for "{{.DEBUG_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.DEBUG_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-unbound:
    desc: 'Provision "Unbound" on "{{.DEBUG_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'unbound'}
