---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  DEVBOX_HOST: "devbox"
  SERVICE_VAR: "{{.DEVBOX_HOST}}"

tasks:
  check:
    desc: 'Check "{{.DEVBOX_HOST}}" host vars'
    cmds:
      - task: shared:check-lxc-vars

  # ? Terraform
  create-lxc:
    desc: 'Create "{{.DEVBOX_HOST}}" host'
    cmds:
      - task: shared:create-lxc

  destroy-lxc:
    desc: 'Destroy "{{.DEVBOX_HOST}}" host'
    cmds:
      - task: shared:destroy-lxc

  update-dns:
    desc: 'Update DNS records for "{{.DEVBOX_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.DEVBOX_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-traefik:
    desc: 'Provision "Traefik" on "{{.DEVBOX_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'traefik'}

  provision-wakapi:
    desc: 'Provision "Wakapi" on "{{.DEVBOX_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'wakapi'}
