---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  GRAFIX_HOST: "grafix"
  SERVICE_VAR: "{{.GRAFIX_HOST}}"

tasks:
  check:
    desc: 'Check "{{.GRAFIX_HOST}}" host vars'
    cmds:
      - task: shared:check-vars

  # ? Terraform
  create-lxc:
    desc: "Create '{{.GRAFIX_HOST}}' host + patch LXC"
    cmds:
      - task: shared:terraform-create
      - task: shared:patch-lxc
        vars: {PATCH_NAME: 'gnu'}

  destroy-lxc:
    desc: 'Destroy "{{.GRAFIX_HOST}}" host'
    cmds:
      - task: shared:terraform-destroy

  update-dns:
    desc: 'Update DNS records for "{{.GRAFIX_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.GRAFIX_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-traefik:
    desc: 'Provision "Traefik" on "{{.GRAFIX_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'traefik'}

  provision-neko:
    desc: 'Provision "Neko" on "{{.GRAFIX_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'neko'}
