---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  NET_HOST: "net"
  SERVICE_VAR: "{{.NET_HOST}}"

tasks:
  check:
    desc: 'Check "{{.NET_HOST}}" host vars'
    cmds:
      - task: shared:check-vars

  # ? Terraform
  create-lxc:
    desc: 'Create "{{.NET_HOST}}" host + patch LXC'
    cmds:
      - task: shared:terraform-create
      - task: shared:patch-lxc
        vars: {PATCH_NAME: 'devtun'}

  destroy-lxc:
    desc: 'Destroy "{{.NET_HOST}}" host'
    cmds:
      - task: shared:terraform-destroy

  update-dns:
    desc: 'Update DNS records for "{{.NET_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.NET_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-tailscale:
    desc: 'Provision "Tailscale" on "{{.NET_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'tailscale'}

  provision-rustdesk:
    desc: 'Provision "RustDesk" on "{{.NET_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'rustdesk'}

  provision-cloudflare-ddns:
    desc: 'Provision "Cloudflare DDNS" on "{{.NET_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'cloudflare_ddns'}
