---
version: '3'

vars:
  ORACLE_VAR: "oracle"
  ORACLE_ANSIBLE_INVENTORY: "inventories/{{.ORACLE_VAR}}"
  ORACLE_ANSIBLE_PLAYBOOK: "{{.ORACLE_VAR}}-provision.yml"

tasks:
  provision:
    dir: "/{{.ANSIBLE_DIR}}"
    desc: Provision Oracle node(s)
    cmds:
      - ansible-playbook -i {{.ORACLE_ANSIBLE_INVENTORY}} {{.ORACLE_ANSIBLE_PLAYBOOK}} {{.O_TAGS| default ""}}
