---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  SERVICE_VAR: 'template'

tasks:
  ansible-proxmox:
    internal: true
    dir: "/{{.ANSIBLE_DIR}}"
    cmds:
      - ansible-playbook -i {{.ANSIBLE_INVENTORY_PROXMOX}} {{.P_PLAYBOOK}} {{.P_TAGS| default ""}}

  list-nodes:
    desc: List Proxmox nodes
    cmds:
      - task: ansible-proxmox
        vars:
          P_PLAYBOOK: 'proxmox-nodes-provision.yml'
          P_TAGS: '--list-hosts'

  provision-nodes:
    desc: Provision Proxmox nodes
    cmds:
      - task: ansible-proxmox
        vars:
          P_PLAYBOOK: 'proxmox-nodes-provision.yml'

  update-nodes:
    desc: Update Proxmox nodes
    cmds:
      - task: ansible-proxmox
        vars:
          P_PLAYBOOK: 'proxmox-nodes-update.yml'

  reboot-nodes:
    desc: Reboot Proxmox nodes
    cmds:
      - task: ansible-proxmox
        vars:
          P_PLAYBOOK: 'proxmox-nodes-reboot.yml'

  provision-pbs:
    desc: Provision PBS
    cmds:
      - task: ansible-proxmox
        vars:
          P_PLAYBOOK: 'proxmox-pbs-provision.yml'

  create-vm-template:
    desc: Provision VM Template
    cmds:
      # First create VM
      - task: shared:terraform-create
      - sleep 10
      # Provision VM
      - task: ansible-proxmox
        vars:
          P_PLAYBOOK: 'proxmox-template-provision.yml'
      - sleep 10
      # Convert VM to a template
      - task: shared:terraform-create
        vars:
          MY_TF_VARS: -var="convert_to_template=true"

  destroy-vm-template:
    desc: Destroy VM Template
    cmds:
      - task: shared:terraform-destroy
