---
version: '3'

vars:
  RPI_VAR: "rpi"
  RPI_TF_DIR: "{{.TERRAFORM_DIR}}/{{.RPI_VAR}}"
  RPI_TF_STATE: "{{.TERRAFORM_STATE}}/{{.RPI_VAR}}.tfstate"
  RPI_ANSIBLE_INVENTORY: "inventories/{{.RPI_VAR}}"
  # ? Pre-provisioned RPis
  RPI_LOCAL_ANSIBLE_PLAYBOOK: "{{.RPI_VAR}}-pre-provision.yml"
  # ? Provisioned RPis
  RPI_ANSIBLE_PLAYBOOK: "{{.RPI_VAR}}-provision.yml"

tasks:
  check:
    desc: "Check '{{.RPI_VAR}}' host vars"
    cmds:
      - "echo RPI_TF_DIR={{.RPI_TF_DIR}}"
      - "echo RPI_TF_STATE={{.RPI_TF_STATE}}"
      - "echo RPI_ANSIBLE_INVENTORY={{.RPI_ANSIBLE_INVENTORY}}"
      - "echo RPI_LOCAL_ANSIBLE_PLAYBOOK={{.RPI_LOCAL_ANSIBLE_PLAYBOOK}}"
      - "echo RPI_ANSIBLE_PLAYBOOK={{.RPI_ANSIBLE_PLAYBOOK}}"

  # ? Terraform
  update-dns:
    desc: "Update DNS records for RPi hosts"
    dir: "{{.RPI_TF_DIR}}"
    preconditions:
      - sh: test -f {{.RPI_TF_STATE}}
        msg: "{{.RPI_TF_STATE}} not found"
    cmds:
      - terraform init -backend-config="path={{.RPI_TF_STATE}}"
      - terraform fmt && terraform validate
      - |
        terraform apply                           \
          -lock=false                             \
          -compact-warnings                       \
          -parallelism=1                          \
          -target=cloudflare_record.cname_records \
          -target=cloudflare_record.dns_record

  ansible-rpi:
    internal: true
    dir: "{{.ANSIBLE_DIR}}"
    cmds:
      - ansible-playbook -i {{.RPI_ANSIBLE_INVENTORY}} {{.R_PLAYBOOK}} {{.R_TAGS:default ""}}

  # ? Ansible (pre-provisioned RPis commands)
  list-rpis-local:
    desc: List RPis local
    cmds:
      - task: ansible-rpi
        vars: {R_PLAYBOOK: { ref: .RPI_LOCAL_ANSIBLE_PLAYBOOK }, R_TAGS: '--list-hosts'}

  pre-provision-rpis:
    desc: Provision RPis
    cmds:
      - task: ansible-rpi
        vars: {R_PLAYBOOK: { ref: .RPI_LOCAL_ANSIBLE_PLAYBOOK }}

  # ? Ansible
  list-rpis:
    desc: List RPis
    cmds:
      - task: ansible-rpi
        vars: {R_PLAYBOOK: { ref: .RPI_ANSIBLE_PLAYBOOK }, R_TAGS: '--list-hosts'}

  provision-rpis:
    desc: Provision RPis
    cmds:
      - task: ansible-rpi
        vars: {R_PLAYBOOK: { ref: .RPI_ANSIBLE_PLAYBOOK }}

  update-rpis:
    desc: Update RPis (alias to 'provision-rpis' task)
    cmds:
      - task: provision-rpis

  provision-traefik:
    desc: "Provision 'Traefik' on RPis"
    cmds:
      - task: ansible-rpi
        vars: {R_PLAYBOOK: { ref: .RPI_ANSIBLE_PLAYBOOK }, R_TAGS: '--tag traefik'}

  provision-pulse:
    desc: "Provision 'Pulse' on RPi"
    cmds:
      - task: ansible-rpi
        vars: {R_PLAYBOOK: { ref: .RPI_ANSIBLE_PLAYBOOK }, R_TAGS: '--tag pulse'}
