---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  TESTVM_HOST: "testvm"
  SERVICE_VAR: "{{.TESTVM_HOST}}"

tasks:
  check:
    desc: 'Check "{{.TESTVM_HOST}}" host vars'
    cmds:
      - task: shared:check-lxc-vars

  # ? Terraform
  create:
    desc: 'Create "{{.TESTVM_HOST}}" host'
    cmds:
      - task: shared:create

  destroy:
    desc: 'Destroy "{{.TESTVM_HOST}}" host'
    cmds:
      - task: shared:destroy

  update-dns:
    desc: 'Update DNS records for "{{.TESTVM_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.TESTVM_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-traefik:
    desc: 'Provision "Traefik" on "{{.TESTVM_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'traefik'}

  provision-wakapi:
    desc: 'Provision "Wakapi" on "{{.TESTVM_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'wakapi'}
