---
version: '3'

includes:
  shared:
    taskfile: ./__shared.yml
    internal: true

vars:
  TOOLS_HOST: "tools"
  SERVICE_VAR: "{{.TOOLS_HOST}}"

tasks:
  check:
    desc: 'Check "{{.TOOLS_HOST}}" host vars'
    cmds:
      - task: shared:check-vars

  # ? Terraform
  create-lxc:
    desc: 'Create "{{.TOOLS_HOST}}" host'
    cmds:
      - task: shared:terraform-create

  destroy-lxc:
    desc: 'Destroy "{{.TOOLS_HOST}}" host'
    cmds:
      - task: shared:terraform-destroy

  update-dns:
    desc: 'Update DNS records for "{{.TOOLS_HOST}}" host'
    cmds:
      - task: shared:update-dns

  # ? Ansible
  provision:
    desc: 'Provision "{{.TOOLS_HOST}}" via Ansible'
    cmds:
      - task: shared:provision

  provision-traefik:
    desc: 'Provision "Traefik" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'traefik'}

  provision-atuin:
    desc: 'Provision "Atuin" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'atuin'}

  provision-dumbpad:
    desc: 'Provision "DumbPad" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'dumbpad'}

  provision-it-tools:
    desc: 'Provision "IT-Tools" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'it_tools'}

  provision-networking-toolbox:
    desc: 'Provision "Networking-Toolbox" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'networking_toolbox'}

  provision-speedtest-tracker:
    desc: 'Provision "Speedtest Tracker" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'speedtest_tracker'}

  provision-termix:
    desc: 'Provision "Termix" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'termix'}

  provision-bichon:
    desc: 'Provision "Bichon" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'bichon'}

  provision-pocket-id:
    desc: 'Provision "Pocket ID" on "{{.TOOLS_HOST}}"'
    cmds:
      - task: shared:provision-app
        vars: {APP_NAME: 'pocket_id'}
