---
doppler_req_pkgs:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
doppler_key_url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key
doppler_key_file: doppler-archive-keyring.key
doppler_gpg_path: /usr/share/keyrings/doppler-archive-keyring.gpg

mise_gpg_url: https://mise.jdx.dev/gpg-key.pub
mise_keyrings_path: /etc/apt/keyrings
mise_keyrings_file: "{{ mise_keyrings_path }}/mise-archive-keyring.asc"

vscode_req_pkgs:
  - apt-transport-https
  - software-properties-common
vscode_key_url: https://packages.microsoft.com/keys/microsoft.asc
vscode_key_path: /etc/apt/keyrings/microsoft.asc
vscode_repos_url: https://github.com/ifarfan/
vscode_repos_folder: /root/repos
vscode_repos:
  - my-homelab

gh_key_url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
gh_gpg_path: /etc/apt/keyrings/githubcli-archive-keyring.gpg

gh_name: "{{ lookup('ansible.builtin.ini', 'name', section='github', file='credentials.ini') }}"
gh_email: "{{ lookup('ansible.builtin.ini', 'email', section='github', file='credentials.ini') }}"
