---
- name: Install pre-reqs
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg

- name: Download repository GPG key
  ansible.builtin.get_url:
    url: https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key
    dest: /tmp/doppler-archive-keyring.key
    mode: 0444
    validate_certs: true

- name: De-armor downloaded key
  ansible.builtin.shell:
    cmd: gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg /tmp/doppler-archive-keyring.key
    creates: /usr/share/keyrings/doppler-archive-keyring.gpg

- name: Add apt repository with signed-by attribute
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64, signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main"
    state: present
    filename: doppler-cli
    update_cache: true

- name: Install Doppler CLI
  ansible.builtin.apt:
    pkg: doppler
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_time }}"

# Debian 11+ / Ubuntu 22.04+
#sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
#curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
#echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
# sudo apt-get update && sudo apt-get install doppler
