---
- name: Configure Doppler
  ansible.builtin.import_tasks: doppler.yml

- name: Configure Mise
  ansible.builtin.import_tasks: mise.yml

- name: Configure VS Code
  ansible.builtin.import_tasks: vscode.yml

- name: Configure Github CLI
  ansible.builtin.import_tasks: gh-cli.yml

- name: Configure Prezto
  ansible.builtin.import_tasks: prezto.yml

- name: Configure dotfiles
  ansible.builtin.import_tasks: dotfiles.yml

- name: Other miscellaneous tasks
  ansible.builtin.import_tasks: miscellaneous.yml
