---
- name: Install NFS client and mount volumes
  ansible.builtin.include_role:
    name: nfs_client
  vars:
    nfs_client_mounts:
      - { volume: devbox, path: /mnt/devbox, rights: rw }

- name: Symlink to mimic MacOS path
  ansible.builtin.file:
    src: /mnt
    dest: /Volumes
    owner: root
    group: root
    state: link

- name: Install Miscellaneous packages
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop: "{{ miscellaneous_pkgs }}"
