---
- name: Install NFS client and mount volumes
  ansible.builtin.include_role:
    name: nfs_client
  vars:
    nfs_client_mounts:
      - { volume: devbox, path: /mnt/devbox, rights: rw }

- name: Symlink to mimic MacOS path
  ansible.builtin.file:
    src: /mnt
    dest: /Volumes
    owner: root
    group: root
    state: link

- name: Create .git directory
  ansible.builtin.file:
    path: "/root/.git"
    state: directory
    mode: 0755

- name: List of local git files
  ansible.builtin.command:
    ls -1 "{{ role_path }}/files/"
  delegate_to: localhost
  become: false
  changed_when: false
  register: git_files

- name: Copy git files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/.git/.{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ git_files.stdout_lines }}"
