---
- name: Install NFS client and mount volumes
  ansible.builtin.include_role:
    name: nfs_client
  vars:
    nfs_client_mounts:
      - { volume: devbox, path: /mnt/devbox, rights: rw }

- name: Symlink to mimic MacOS path
  ansible.builtin.file:
    src: /mnt
    dest: /Volumes
    owner: root
    group: root
    state: link

- name: Copy git config
  ansible.builtin.template:
    src: gitconfig.j2
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: 0644

- name: Copy global git ignore
  ansible.builtin.copy:
    src: gitignore_global
    dest: /root/.gitignore_global
    owner: root
    group: root
    mode: 0644
